-- ============================================================================
-- Shyamali Krishna Automobile — data export
-- Source: https://umshexyaeybbmyzwjngx.supabase.co
--
-- Runnable seed for a fresh Supabase project. Run AFTER the schema migration
-- that creates these tables. Every statement is ON CONFLICT DO NOTHING, so
-- re-running it will not duplicate or overwrite anything.
-- ============================================================================

begin;

-- site_settings: 12 row(s)
insert into public.site_settings (key, value, created_at, updated_at) values ('phone', '+91 7488095803', '2026-08-11T15:51:34.75285+00:00', '2026-08-11T15:51:34.75285+00:00') on conflict (key) do nothing;
insert into public.site_settings (key, value, created_at, updated_at) values ('email', 'info@shyamalikrishna.com', '2026-08-11T15:51:34.75285+00:00', '2026-08-11T15:51:34.75285+00:00') on conflict (key) do nothing;
insert into public.site_settings (key, value, created_at, updated_at) values ('whatsapp', '+91 7488095803', '2026-08-11T15:51:34.75285+00:00', '2026-08-11T15:51:34.75285+00:00') on conflict (key) do nothing;
insert into public.site_settings (key, value, created_at, updated_at) values ('office_line1', 'C/O Anurag Vasista', '2026-08-11T15:51:34.75285+00:00', '2026-08-11T15:51:34.75285+00:00') on conflict (key) do nothing;
insert into public.site_settings (key, value, created_at, updated_at) values ('office_line2', 'KH-56, PLTO-357, Kendua', '2026-08-11T15:51:34.75285+00:00', '2026-08-11T15:51:34.75285+00:00') on conflict (key) do nothing;
insert into public.site_settings (key, value, created_at, updated_at) values ('office_line3', 'Nawada, Dist-Nawada', '2026-08-11T15:51:34.75285+00:00', '2026-08-11T15:51:34.75285+00:00') on conflict (key) do nothing;
insert into public.site_settings (key, value, created_at, updated_at) values ('office_line4', 'Bihar 805110, India', '2026-08-11T15:51:34.75285+00:00', '2026-08-11T15:51:34.75285+00:00') on conflict (key) do nothing;
insert into public.site_settings (key, value, created_at, updated_at) values ('gst', '10ABUCS4908F1ZA', '2026-08-11T15:51:34.75285+00:00', '2026-08-11T15:51:34.75285+00:00') on conflict (key) do nothing;
insert into public.site_settings (key, value, created_at, updated_at) values ('legal_name', 'Shyamali Krishna Automobile Private Limited', '2026-08-11T15:51:34.75285+00:00', '2026-08-11T15:51:34.75285+00:00') on conflict (key) do nothing;
insert into public.site_settings (key, value, created_at, updated_at) values ('hours_weekday', 'Monday–Saturday: 9:00 AM–7:00 PM', '2026-08-11T15:51:34.75285+00:00', '2026-08-11T15:51:34.75285+00:00') on conflict (key) do nothing;
insert into public.site_settings (key, value, created_at, updated_at) values ('hours_sunday', 'Sunday: On appointment', '2026-08-11T15:51:34.75285+00:00', '2026-08-11T15:51:34.75285+00:00') on conflict (key) do nothing;
insert into public.site_settings (key, value, created_at, updated_at) values ('maps_query', 'Nawada, Bihar, India', '2026-08-11T15:51:34.75285+00:00', '2026-08-11T15:51:34.75285+00:00') on conflict (key) do nothing;

-- categories: 6 row(s)
insert into public.categories (id, name, name_hi, slug, description, description_hi, short_description, short_description_hi, icon, display_order, seo_title, seo_description, image_url, created_at, updated_at) values ('ce71f1a1-2b53-46d4-9b0a-f992ca67e07c', 'Tillage & Soil Preparation', null, 'tillage-soil-preparation', 'Implements that prepare the soil for sowing — rotavators, ploughs, and cultivators that create the optimal seedbed across varied Bihar soil conditions.', null, 'Rotavators, MB ploughs, and primary tillage implements for seedbed preparation.', null, 'shovel', 1, null, null, null, '2026-08-11T15:51:34.75285+00:00', '2026-08-11T15:51:34.75285+00:00') on conflict (id) do nothing;
insert into public.categories (id, name, name_hi, slug, description, description_hi, short_description, short_description_hi, icon, display_order, seo_title, seo_description, image_url, created_at, updated_at) values ('f270301d-b457-466a-bdbc-d4c0f8bc60d8', 'Sowing & Seeding', null, 'sowing-seeding', 'Implements that place seed accurately and at the right depth for optimal germination, including super seeders and seed-cum-fertiliser drills.', null, 'Precision seeders and seed-cum-fertiliser drills for accurate planting.', null, 'sprout', 2, null, null, null, '2026-08-11T15:51:34.75285+00:00', '2026-08-11T15:51:34.75285+00:00') on conflict (id) do nothing;
insert into public.categories (id, name, name_hi, slug, description, description_hi, short_description, short_description_hi, icon, display_order, seo_title, seo_description, image_url, created_at, updated_at) values ('9c686163-2d53-4afb-ac37-a67288a018e6', 'Crop Residue Management', null, 'residue-management', 'Equipment that manages crop residue without burning — Happy Seeders and straw reapers that support sustainable stubble management and soil conservation.', null, 'Happy Seeders and straw reapers for in-situ stubble handling.', null, 'leaf', 3, null, null, null, '2026-08-11T15:51:34.75285+00:00', '2026-08-11T15:51:34.75285+00:00') on conflict (id) do nothing;
insert into public.categories (id, name, name_hi, slug, description, description_hi, short_description, short_description_hi, icon, display_order, seo_title, seo_description, image_url, created_at, updated_at) values ('58d5db09-aec7-429f-88d7-acb4b39fde08', 'Harvesting Machinery', null, 'harvesting', 'Self-propelled and tractor-operated harvesters that bring speed and efficiency to the harvest stage, reducing grain loss and labour dependency.', null, 'Combine harvesters and reaping equipment for efficient crop harvest.', null, 'wheat', 4, null, null, null, '2026-08-11T15:51:34.75285+00:00', '2026-08-11T15:51:34.75285+00:00') on conflict (id) do nothing;
insert into public.categories (id, name, name_hi, slug, description, description_hi, short_description, short_description_hi, icon, display_order, seo_title, seo_description, image_url, created_at, updated_at) values ('eeba2620-9893-4e10-b417-91e8d8aa89a0', 'Post-Harvest & Threshing', null, 'post-harvest', 'Threshers and post-harvest implements that separate grain from stalk, cleaning and preparing produce for market or storage.', null, 'Threshers and post-harvest equipment for grain separation.', null, 'package', 5, null, null, null, '2026-08-11T15:51:34.75285+00:00', '2026-08-11T15:51:34.75285+00:00') on conflict (id) do nothing;
insert into public.categories (id, name, name_hi, slug, description, description_hi, short_description, short_description_hi, icon, display_order, seo_title, seo_description, image_url, created_at, updated_at) values ('9deabdc7-e8d6-4307-95fd-67290d5ba3d5', 'Specialist Implements', null, 'specialist-implements', 'Implements engineered for specific applications — ditchers, ridgers, levellers, and custom tools that address particular field requirements.', null, 'Purpose-built tools for specific crops, soils, and operations.', null, 'wrench', 6, null, null, null, '2026-08-11T15:51:34.75285+00:00', '2026-08-11T15:51:34.75285+00:00') on conflict (id) do nothing;

-- partners: 6 row(s)
insert into public.partners (id, name, name_hi, slug, tagline, tagline_hi, positioning, positioning_hi, overview, overview_hi, partnership_context, partnership_context_hi, why_partnership_matters, why_partnership_matters_hi, origin_country, logo_url, hero_image_url, seo_title, seo_description, display_order, created_at, updated_at) values ('04f078d0-8c50-441d-bd7f-eaa675976d0e', 'Maschio Gaspardo', null, 'maschio-gaspardo', 'Italian engineering for Indian fields', null, 'World-renowned Italian manufacturer of tillage, seeding, and crop-residue implements, distributed in Bihar by Shyamali Krishna Automobile.', null, 'Maschio Gaspardo is one of the world''s leading manufacturers of agricultural implements, headquartered in Campoodile (Padua), Italy. The group designs and manufactures rotavators, ploughs, seeders, power harrows, and crop-residue equipment distributed across more than 100 countries. Shyamali Krishna Automobile brings select Maschio Gaspardo implements to Bihar, offering farmers access to Italian-engineered machinery backed by regional service and parts support.', null, null, null, null, null, 'Italy', null, null, null, null, 1, '2026-08-11T15:51:34.75285+00:00', '2026-08-11T15:51:34.75285+00:00') on conflict (id) do nothing;
insert into public.partners (id, name, name_hi, slug, tagline, tagline_hi, positioning, positioning_hi, overview, overview_hi, partnership_context, partnership_context_hi, why_partnership_matters, why_partnership_matters_hi, origin_country, logo_url, hero_image_url, seo_title, seo_description, display_order, created_at, updated_at) values ('04526cb9-431b-474c-b4b4-f79c5a4404fc', 'Sitara AgroTech', null, 'sitara-agrotech', 'Reliable harvesting and chaff-cutting solutions', null, 'Indian manufacturer of straw reapers, chaff cutters, and harvesting-related implements, serving Bihar farmers through Shyamali Krishna Automobile.', null, 'Sitara AgroTech manufactures harvesting and forage equipment including straw reapers and chaff cutters designed for Indian field conditions. The company focuses on practical, durable machinery suited to small and medium farm operations. Shyamali Krishna Automobile offers Sitara AgroTech products with local availability of parts and service support.', null, null, null, null, null, 'India', null, null, null, null, 2, '2026-08-11T15:51:34.75285+00:00', '2026-08-11T15:51:34.75285+00:00') on conflict (id) do nothing;
insert into public.partners (id, name, name_hi, slug, tagline, tagline_hi, positioning, positioning_hi, overview, overview_hi, partnership_context, partnership_context_hi, why_partnership_matters, why_partnership_matters_hi, origin_country, logo_url, hero_image_url, seo_title, seo_description, display_order, created_at, updated_at) values ('24b6130f-1275-4e91-9c38-1ffb5881cf58', 'Gobind Alloys (Govind)', null, 'govind', 'Threshing solutions built for Indian harvests', null, 'Manufacturer of the Super Shakti range of threshers, distributed in Bihar by Shyamali Krishna Automobile.', null, 'Gobind Alloys, known by its Govind brand, manufactures threshers and post-harvest equipment designed for Indian grain crops. The Super Shakti thresher line is built for durability and throughput across wheat, paddy, and pulses. Shyamali Krishna Automobile makes Govind threshers available to Bihar farmers with regional after-sales support.', null, null, null, null, null, 'India', null, null, null, null, 3, '2026-08-11T15:51:34.75285+00:00', '2026-08-11T15:51:34.75285+00:00') on conflict (id) do nothing;
insert into public.partners (id, name, name_hi, slug, tagline, tagline_hi, positioning, positioning_hi, overview, overview_hi, partnership_context, partnership_context_hi, why_partnership_matters, why_partnership_matters_hi, origin_country, logo_url, hero_image_url, seo_title, seo_description, display_order, created_at, updated_at) values ('ea12b412-1974-481e-be39-6b2f3968c14e', 'Agrimax', null, 'agrimax', 'Dependable tillage and cultivation implements', null, 'Manufacturer of cultivators and tillage implements for Bihar soil conditions, offered through Shyamali Krishna Automobile.', null, 'Agrimax manufactures cultivators and tillage implements suited to Indian soil types and tractor power ranges. The company focuses on robust, serviceable equipment for everyday field operations. Shyamali Krishna Automobile supplies Agrimax cultivators across Bihar with parts and service backup.', null, null, null, null, null, 'India', null, null, null, null, 4, '2026-08-11T15:51:34.75285+00:00', '2026-08-11T15:51:34.75285+00:00') on conflict (id) do nothing;
insert into public.partners (id, name, name_hi, slug, tagline, tagline_hi, positioning, positioning_hi, overview, overview_hi, partnership_context, partnership_context_hi, why_partnership_matters, why_partnership_matters_hi, origin_country, logo_url, hero_image_url, seo_title, seo_description, display_order, created_at, updated_at) values ('be5c0ce6-1141-448d-892c-9e8cc963a0b8', 'Hazarix', null, 'hazarix', 'Specialist implements for specific field requirements', null, 'Manufacturer of specialist agricultural implements, offered in Bihar through Shyamali Krishna Automobile.', null, 'Hazarix manufactures a range of specialist agricultural implements designed for specific field operations and crop requirements. The product line includes tools for ridge making, ditching, levelling, and other targeted applications. Shyamali Krishna Automobile brings Hazarix specialist implements to Bihar farmers with local support.', null, null, null, null, null, 'India', null, null, null, null, 5, '2026-08-11T15:51:34.75285+00:00', '2026-08-11T15:51:34.75285+00:00') on conflict (id) do nothing;
insert into public.partners (id, name, name_hi, slug, tagline, tagline_hi, positioning, positioning_hi, overview, overview_hi, partnership_context, partnership_context_hi, why_partnership_matters, why_partnership_matters_hi, origin_country, logo_url, hero_image_url, seo_title, seo_description, display_order, created_at, updated_at) values ('f857f966-dc9b-43a9-9f70-147616318f8a', 'Select Harvester OEMs', null, 'harvester-oems', 'Harvesting machinery from multiple proven manufacturers', null, 'A curated range of harvesting equipment from established manufacturers, offered in Bihar through Shyamali Krishna Automobile.', null, 'Shyamali Krishna Automobile offers harvesting machinery from multiple established manufacturers, selected for suitability to Bihar crop patterns, field sizes, and operating conditions. This multi-OEM approach allows farmers and custom-hiring operators to choose harvesters matched to their specific requirements rather than being limited to a single brand.', null, null, null, null, null, 'India', null, null, null, null, 6, '2026-08-11T15:51:34.75285+00:00', '2026-08-11T15:51:34.75285+00:00') on conflict (id) do nothing;

-- products: 10 row(s)
insert into public.products (id, name, name_hi, slug, category_id, partner_id, positioning, positioning_hi, overview, overview_hi, features, features_hi, benefits, benefits_hi, applications, applications_hi, crops, soil_conditions, operator_scale, tractor_hp, working_width, weight, blade_tine_config, gearbox_drive, rpm, warranty, financing, financing_hi, subsidy, subsidy_hi, primary_image_url, gallery_images, seo_title, seo_description, is_published, display_order, created_at, updated_at) values ('ab39ab52-87f1-470d-aeb7-953a277a76ee', 'Maschio Gaspardo MB Plough', null, 'maschio-gaspardo-mb-plough', 'ce71f1a1-2b53-46d4-9b0a-f992ca67e07c', '04f078d0-8c50-441d-bd7f-eaa675976d0e', 'Mouldboard plough for deep primary tillage and inverted furrow turning.', null, 'The MB (mouldboard) plough is a primary tillage implement that inverts and breaks the soil, burying weeds and crop residue to a depth that improves soil structure. It is used for deep tillage in harder soils and for opening new land. The plough turns the furrow slice, creating a clean, inverted seedbed base.', null, 'Hardened mouldboard and share for durability; shear bolt protection against obstacles; adjustable working depth; heavy-duty frame; reversible plough option available for two-way turning.', null, 'Deep tillage for improved soil structure; buries weeds and residue; suitable for harder and heavier soils; creates clean inverted tilth for subsequent operations.', null, 'Primary tillage; deep ploughing for paddy and wheat fields; weed and residue burial; land preparation for new cultivation.', null, 'Paddy, wheat, sugarcane, general', null, null, '50–70 HP', null, null, null, null, null, null, null, null, null, null, '/mb-plough.webp', null, null, null, true, 4, '2026-08-11T15:51:34.75285+00:00', '2026-08-11T15:51:34.75285+00:00') on conflict (id) do nothing;
insert into public.products (id, name, name_hi, slug, category_id, partner_id, positioning, positioning_hi, overview, overview_hi, features, features_hi, benefits, benefits_hi, applications, applications_hi, crops, soil_conditions, operator_scale, tractor_hp, working_width, weight, blade_tine_config, gearbox_drive, rpm, warranty, financing, financing_hi, subsidy, subsidy_hi, primary_image_url, gallery_images, seo_title, seo_description, is_published, display_order, created_at, updated_at) values ('8304e97f-25ae-4e23-b394-feab088b8a3d', 'Maschio Gaspardo Happy Seeder', null, 'maschio-gaspardo-happy-seeder', '9c686163-2d53-4afb-ac37-a67288a018e6', '04f078d0-8c50-441d-bd7f-eaa675976d0e', 'Residue-managed sowing implement that eliminates the need for stubble burning.', null, 'The Happy Seeder is designed to sow wheat directly into standing paddy stubble without burning. It cuts and lifts the residue, opens a slit in the soil, places the seed, and deposits the loose residue back over the sown row as mulch. This eliminates the need for stubble burning, conserves soil organic matter, and reduces smoke and environmental damage.', null, 'Front rotor that cuts and lifts paddy stubble; rear sowing tines that place seed into the slit; residue is deposited back as mulch; adjustable sowing depth; compatible with standard tractor three-point linkage.', null, 'Eliminates stubble burning; conserves soil moisture and organic matter; reduces air pollution; saves time and cost compared to conventional clearing and sowing; single-pass operation.', null, 'Direct sowing of wheat into paddy stubble; residue-managed cultivation; conservation agriculture practices.', null, 'Wheat (into paddy stubble)', null, null, '45–60 HP', null, null, null, null, null, null, null, null, null, null, '/happy-seeder.webp', null, null, null, true, 3, '2026-08-11T15:51:34.75285+00:00', '2026-08-11T15:51:34.75285+00:00') on conflict (id) do nothing;
insert into public.products (id, name, name_hi, slug, category_id, partner_id, positioning, positioning_hi, overview, overview_hi, features, features_hi, benefits, benefits_hi, applications, applications_hi, crops, soil_conditions, operator_scale, tractor_hp, working_width, weight, blade_tine_config, gearbox_drive, rpm, warranty, financing, financing_hi, subsidy, subsidy_hi, primary_image_url, gallery_images, seo_title, seo_description, is_published, display_order, created_at, updated_at) values ('ba022fc9-d7d4-4703-8c2d-86cc000fcb14', 'Sitara AgroTech Chaff Cutter', null, 'sitara-agrotech-chaff-cutter', 'eeba2620-9893-4e10-b417-91e8d8aa89a0', '04526cb9-431b-474c-b4b4-f79c5a4404fc', 'Reliable chaff cutter for preparing uniform fodder from crop residue.', null, 'The Sitara AgroTech Chaff Cutter is designed to cut dry and green fodder into uniform pieces suitable for livestock feed. It is built for continuous operation on farms and custom-hiring operations, offering a practical solution for fodder preparation.', null, 'Sharp hardened blades; adjustable cut length; flywheel for smooth operation; feed roller for consistent input; robust frame; belt drive from tractor or motor.', null, 'Produces uniform fodder for livestock; reduces fodder waste; supports continuous operation; adjustable cut length for different feed requirements.', null, 'Fodder preparation for dairy and livestock; chopping dry and green fodder; farm-level feed processing.', null, 'All fodder crops', null, null, '15–30 HP', null, null, null, null, null, null, null, null, null, null, '/chaff-cutter.webp', null, null, null, true, 6, '2026-08-11T15:51:34.75285+00:00', '2026-08-11T15:51:34.75285+00:00') on conflict (id) do nothing;
insert into public.products (id, name, name_hi, slug, category_id, partner_id, positioning, positioning_hi, overview, overview_hi, features, features_hi, benefits, benefits_hi, applications, applications_hi, crops, soil_conditions, operator_scale, tractor_hp, working_width, weight, blade_tine_config, gearbox_drive, rpm, warranty, financing, financing_hi, subsidy, subsidy_hi, primary_image_url, gallery_images, seo_title, seo_description, is_published, display_order, created_at, updated_at) values ('6a71a93f-4984-476b-bfc3-1b24d995e349', 'Maschio Gaspardo Rotavator', null, 'maschio-gaspardo-rotavator', 'ce71f1a1-2b53-46d4-9b0a-f992ca67e07c', '04f078d0-8c50-441d-bd7f-eaa675976d0e', 'Italian-engineered rotavator for fine seedbed preparation across varied Bihar soils.', null, 'The Maschio Gaspardo rotavator is a tractor-operated rotary tiller that prepares a fine, level seedbed in a single pass. It uses a multi-blade rotor that breaks, mixes, and levels soil, reducing the number of tillage operations needed before sowing. Designed for durability and consistent performance, it is suited to a range of soil types found across Bihar and adjoining regions.', null, 'Multi-blade rotor for thorough soil pulverisation; hardened blades for extended wear life; adjustable working depth; side transmission with oil-bath gears; heavy-duty frame for sustained field use.', null, 'Reduces number of tillage passes; creates a fine, uniform seedbed; conserves soil moisture by mixing residue into the tilth; saves fuel and time compared to multiple conventional operations.', null, 'Primary and secondary tillage; seedbed preparation before sowing of wheat, paddy, vegetables, and other crops; incorporation of crop residue and green manure.', null, 'Wheat, paddy, maize, vegetables, pulses', null, null, '40–60 HP', null, null, null, null, null, null, null, null, null, null, '/rotavator.webp', null, null, null, true, 1, '2026-08-11T15:51:34.75285+00:00', '2026-08-11T15:51:34.75285+00:00') on conflict (id) do nothing;
insert into public.products (id, name, name_hi, slug, category_id, partner_id, positioning, positioning_hi, overview, overview_hi, features, features_hi, benefits, benefits_hi, applications, applications_hi, crops, soil_conditions, operator_scale, tractor_hp, working_width, weight, blade_tine_config, gearbox_drive, rpm, warranty, financing, financing_hi, subsidy, subsidy_hi, primary_image_url, gallery_images, seo_title, seo_description, is_published, display_order, created_at, updated_at) values ('54d87d3b-1794-45e2-bd09-41bcb17dd533', 'Maschio Gaspardo Super Seeder', null, 'maschio-gaspardo-super-seeder', 'f270301d-b457-466a-bdbc-d4c0f8bc60d8', '04f078d0-8c50-441d-bd7f-eaa675976d0e', 'Precision seed-cum-fertiliser drill that sows directly into residue-managed fields.', null, 'The Super Seeder combines seed placement and fertiliser application in a single pass, designed for direct sowing after residue management. It opens a precise furrow, drops seed at controlled depth and spacing, places fertiliser separately, and covers the row — all in one operation. This makes it suitable for farmers practising residue-managed sowing to save time, conserve moisture, and reduce field traffic.', null, 'Accurate seed metering with adjustable row spacing; separate fertiliser placement; press wheels for firm soil-to-seed contact; robust furrow openers; calibrated seed and fertiliser hoppers.', null, 'Saves time and fuel by combining sowing and fertiliser application; improves germination through consistent seed depth; reduces moisture loss; supports residue-managed sowing without burning.', null, 'Direct sowing of wheat after residue management; sowing with simultaneous fertiliser application; suitable for paddy-wheat rotation systems.', null, 'Wheat, paddy, maize, pulses', null, null, '40–50 HP', null, null, null, null, null, null, null, null, null, null, '/super-seeder.webp', null, null, null, true, 2, '2026-08-11T15:51:34.75285+00:00', '2026-08-11T15:51:34.75285+00:00') on conflict (id) do nothing;
insert into public.products (id, name, name_hi, slug, category_id, partner_id, positioning, positioning_hi, overview, overview_hi, features, features_hi, benefits, benefits_hi, applications, applications_hi, crops, soil_conditions, operator_scale, tractor_hp, working_width, weight, blade_tine_config, gearbox_drive, rpm, warranty, financing, financing_hi, subsidy, subsidy_hi, primary_image_url, gallery_images, seo_title, seo_description, is_published, display_order, created_at, updated_at) values ('d845bec3-602b-4bc7-9521-bdcf7aea9696', 'Sitara AgroTech Straw Reaper', null, 'sitara-agrotech-straw-reaper', '9c686163-2d53-4afb-ac37-a67288a018e6', '04526cb9-431b-474c-b4b4-f79c5a4404fc', 'Tractor-operated straw reaper that harvests, threshes, and chops standing stubble.', null, 'The Sitara AgroTech Straw Reaper is a tractor-operated implement that cuts standing wheat stubble after harvest, threshes any remaining grain, and chops the straw into uniform pieces suitable for fodder. It performs harvesting, threshing, and straw chopping in a single pass, making it efficient for post-harvest field operations.', null, 'Front cutter bar for standing stubble; threshing drum for residual grain recovery; straw chopping blower; grain collection bag; heavy-duty gearbox; adjustable cutting height.', null, 'Recovers residual grain left after harvest; produces clean chopped straw for fodder; single-pass operation saves time; reduces field waste.', null, 'Post-harvest stubble recovery; straw chopping for fodder; residual grain collection after wheat harvest.', null, 'Wheat, paddy', null, null, '35–50 HP', null, null, null, null, null, null, null, null, null, null, '/straw-reaper.webp', null, null, null, true, 5, '2026-08-11T15:51:34.75285+00:00', '2026-08-11T15:51:34.75285+00:00') on conflict (id) do nothing;
insert into public.products (id, name, name_hi, slug, category_id, partner_id, positioning, positioning_hi, overview, overview_hi, features, features_hi, benefits, benefits_hi, applications, applications_hi, crops, soil_conditions, operator_scale, tractor_hp, working_width, weight, blade_tine_config, gearbox_drive, rpm, warranty, financing, financing_hi, subsidy, subsidy_hi, primary_image_url, gallery_images, seo_title, seo_description, is_published, display_order, created_at, updated_at) values ('fa587cb7-3237-4cef-b118-cd0047969461', 'Govind Super Shakti Thresher', null, 'govind-super-shakti-thresher', 'eeba2620-9893-4e10-b417-91e8d8aa89a0', '24b6130f-1275-4e91-9c38-1ffb5881cf58', 'Durable thresher for efficient grain separation from wheat, paddy, and pulses.', null, 'The Govind Super Shakti Thresher is a tractor-operated or electric thresher designed to separate grain from harvested crop with high throughput and low grain loss. It handles wheat, paddy, and pulses, producing clean grain while chopping straw into fodder. The machine is built for durability and extended operation during the harvest season.', null, 'Heavy-duty threshing cylinder; concave for efficient grain separation; cleaning blower for chaff-free grain; straw outlet for fodder collection; robust bearings and drive system; wheel-mounted for field mobility.', null, 'High throughput for time-critical harvest; low grain loss; clean threshed grain; chopped straw as by-product fodder; suitable for custom-hiring operations.', null, 'Threshing of wheat, paddy, and pulses; post-harvest grain separation; custom threshing services.', null, 'Wheat, paddy, pulses, maize', null, null, '35–50 HP', null, null, null, null, null, null, null, null, null, null, '/thresher.webp', null, null, null, true, 7, '2026-08-11T15:51:34.75285+00:00', '2026-08-11T15:51:34.75285+00:00') on conflict (id) do nothing;
insert into public.products (id, name, name_hi, slug, category_id, partner_id, positioning, positioning_hi, overview, overview_hi, features, features_hi, benefits, benefits_hi, applications, applications_hi, crops, soil_conditions, operator_scale, tractor_hp, working_width, weight, blade_tine_config, gearbox_drive, rpm, warranty, financing, financing_hi, subsidy, subsidy_hi, primary_image_url, gallery_images, seo_title, seo_description, is_published, display_order, created_at, updated_at) values ('83dfc5f0-8e74-42e5-b33d-fa957e0d27b1', 'Hazarix Specialist Implements', null, 'hazarix-specialist-implements', '9deabdc7-e8d6-4307-95fd-67290d5ba3d5', 'be5c0ce6-1141-448d-892c-9e8cc963a0b8', 'Purpose-built implements for ridge making, ditching, levelling, and targeted field operations.', null, 'Hazarix manufactures a range of specialist implements designed for specific field operations that standard tillage equipment does not cover. These include ridge makers, ditchers, levellers, and other tools suited to particular crops, irrigation methods, or soil management practices. Shyamali Krishna Automobile offers Hazarix specialist implements to Bihar farmers with local support.', null, 'Purpose-built for specific operations; robust construction; compatible with standard tractor linkage; available in multiple sizes and configurations.', null, 'Enables field operations not covered by general tillage equipment; supports targeted crop and soil management; improves efficiency of specific tasks.', null, 'Ridge making for vegetables and sugarcane; ditching for drainage and irrigation; field levelling; crop-specific operations.', null, 'Varies by implement', null, null, 'Varies by implement', null, null, null, null, null, null, null, null, null, null, '/hazarix-implements.webp', null, null, null, true, 9, '2026-08-11T15:51:34.75285+00:00', '2026-08-11T15:51:34.75285+00:00') on conflict (id) do nothing;
insert into public.products (id, name, name_hi, slug, category_id, partner_id, positioning, positioning_hi, overview, overview_hi, features, features_hi, benefits, benefits_hi, applications, applications_hi, crops, soil_conditions, operator_scale, tractor_hp, working_width, weight, blade_tine_config, gearbox_drive, rpm, warranty, financing, financing_hi, subsidy, subsidy_hi, primary_image_url, gallery_images, seo_title, seo_description, is_published, display_order, created_at, updated_at) values ('e73c74ab-9312-4e49-89b2-b6fd857fc29b', 'Harvester Equipment', null, 'harvester-equipment', '58d5db09-aec7-429f-88d7-acb4b39fde08', 'f857f966-dc9b-43a9-9f70-147616318f8a', 'Multi-OEM harvesting machinery matched to Bihar crop patterns and field conditions.', null, 'Shyamali Krishna Automobile offers harvesting machinery from multiple established manufacturers, selected for suitability to Bihar crop patterns, field sizes, and operating conditions. The multi-OEM approach allows farmers and custom-hiring operators to choose harvesters matched to their specific requirements rather than being limited to a single brand. Enquiries are assessed on a per-requirement basis to recommend the most suitable equipment.', null, 'Multiple OEM options; suited to different crop types and field sizes; tractor-operated and self-propelled configurations; regional parts and service support.', null, 'Reduces harvest time and labour dependency; minimises grain loss; suited to different farm scales; local service backup across Bihar.', null, 'Harvesting of paddy, wheat, and other grain crops; custom-hiring operations; institutional and bulk harvesting.', null, 'Paddy, wheat, maize', null, null, 'Varies by model', null, null, null, null, null, null, null, null, null, null, '/harvester.webp', null, null, null, true, 10, '2026-08-11T15:51:34.75285+00:00', '2026-08-11T15:51:34.75285+00:00') on conflict (id) do nothing;
insert into public.products (id, name, name_hi, slug, category_id, partner_id, positioning, positioning_hi, overview, overview_hi, features, features_hi, benefits, benefits_hi, applications, applications_hi, crops, soil_conditions, operator_scale, tractor_hp, working_width, weight, blade_tine_config, gearbox_drive, rpm, warranty, financing, financing_hi, subsidy, subsidy_hi, primary_image_url, gallery_images, seo_title, seo_description, is_published, display_order, created_at, updated_at) values ('ac48f32c-422d-493c-9069-94b1167be7c3', 'Agrimax Cultivator', null, 'agrimax-cultivator', 'ce71f1a1-2b53-46d4-9b0a-f992ca67e07c', 'ea12b412-1974-481e-be39-6b2f3968c14e', 'Robust cultivator for secondary tillage, weed control, and seedbed finishing.', null, 'The Agrimax Cultivator is a tractor-operated secondary tillage implement with rigid or spring-loaded tines that loosen soil, uproot weeds, and prepare a fine seedbed. It is used after primary tillage to break clods and create a uniform tilth suitable for sowing. The cultivator is suited to a range of Bihar soil types and tractor power ranges.', null, 'Spring-loaded or rigid tines for reliable soil engagement; reversible shovel points for extended wear; adjustable tine spacing; heavy-duty frame; three-point linkage compatibility.', null, 'Loosens soil and breaks clods; uproots weeds; prepares fine seedbed; fuel-efficient compared to rotavator for lighter tillage; suitable for repeated inter-culture.', null, 'Secondary tillage; weed control; seedbed finishing; inter-culture operations.', null, 'All crops', null, null, '30–50 HP', null, null, null, null, null, null, null, null, null, null, '/cultivator.webp', null, null, null, true, 8, '2026-08-11T15:51:34.75285+00:00', '2026-08-11T15:51:34.75285+00:00') on conflict (id) do nothing;

-- services: 5 row(s)
insert into public.services (id, name, name_hi, slug, short_description, short_description_hi, overview, overview_hi, what_we_cover, what_we_cover_hi, icon, seo_title, seo_description, display_order, created_at, updated_at) values ('4e1f7dc2-58cd-4e23-b677-b7ef9ae58763', 'Sales & Consultation', null, 'sales-consultation', 'Helping you select the right implement for your soil, crop, and tractor.', null, 'We help farmers, custom-hiring operators, and institutional buyers select the right machinery for their specific requirements. Rather than pushing a single brand, we assess your soil type, crop rotation, tractor power, and operating scale to recommend the most suitable implement from our multi-OEM portfolio.', null, 'Requirement assessment; product demonstration and field visit; tractor compatibility check; multi-OEM comparison; purchase documentation support.', null, 'handshake', null, null, 1, '2026-08-11T15:51:34.75285+00:00', '2026-08-11T15:51:34.75285+00:00') on conflict (id) do nothing;
insert into public.services (id, name, name_hi, slug, short_description, short_description_hi, overview, overview_hi, what_we_cover, what_we_cover_hi, icon, seo_title, seo_description, display_order, created_at, updated_at) values ('637b7a59-5186-4e55-a2bb-5f6c2dd609fe', 'After-Sales Service', null, 'after-sales-service', 'Regional service support to keep your machinery working through the season.', null, 'We provide after-sales service for the machinery we supply, with technicians familiar with the implements and access to genuine parts. Our service support is designed to minimise downtime during critical field operations.', null, 'Scheduled servicing; breakdown support; field visit by technician; maintenance guidance; seasonal readiness checks.', null, 'wrench', null, null, 2, '2026-08-11T15:51:34.75285+00:00', '2026-08-11T15:51:34.75285+00:00') on conflict (id) do nothing;
insert into public.services (id, name, name_hi, slug, short_description, short_description_hi, overview, overview_hi, what_we_cover, what_we_cover_hi, icon, seo_title, seo_description, display_order, created_at, updated_at) values ('0e91b118-635c-4bd5-941b-4e85d83b3cd7', 'Spare Parts', null, 'spare-parts', 'Genuine parts and wear components for the implements we supply.', null, 'We maintain a stock of genuine spare parts and wear components for the machinery we supply. Using genuine blades, tines, bearings, and other consumables preserves performance and extends implement life.', null, 'Genuine OEM parts; blades, tines, and shares; bearings and transmission components; seals and belts; parts identification support.', null, 'package', null, null, 3, '2026-08-11T15:51:34.75285+00:00', '2026-08-11T15:51:34.75285+00:00') on conflict (id) do nothing;
insert into public.services (id, name, name_hi, slug, short_description, short_description_hi, overview, overview_hi, what_we_cover, what_we_cover_hi, icon, seo_title, seo_description, display_order, created_at, updated_at) values ('97e7210f-4562-4657-a7f5-f95b1882b285', 'Finance & EMI', null, 'finance-emi', 'Financing assistance to help you acquire machinery without upfront burden.', null, 'We assist farmers in accessing financing options for machinery purchases, working with financing channels to facilitate tractor-implement loans and EMI arrangements. We help you understand the documentation required and coordinate the process.', null, 'Financing documentation guidance; EMI option coordination; loan process support; coordination with financing partners.', null, 'banknote', null, null, 4, '2026-08-11T15:51:34.75285+00:00', '2026-08-11T15:51:34.75285+00:00') on conflict (id) do nothing;
insert into public.services (id, name, name_hi, slug, short_description, short_description_hi, overview, overview_hi, what_we_cover, what_we_cover_hi, icon, seo_title, seo_description, display_order, created_at, updated_at) values ('704d955e-4d7f-490c-8c89-373ab1bad139', 'Government Subsidy Assistance', null, 'subsidy-assistance', 'Support in navigating applicable farm machinery subsidy schemes.', null, 'We help farmers understand and apply for applicable government subsidy schemes for agricultural machinery. We provide information on scheme eligibility, documentation, and the application process, and coordinate where required.', null, 'Subsidy scheme information; eligibility assessment; documentation support; application coordination; follow-up on approval status.', null, 'landmark', null, null, 5, '2026-08-11T15:51:34.75285+00:00', '2026-08-11T15:51:34.75285+00:00') on conflict (id) do nothing;

-- resources: no rows

-- faqs: 8 row(s)
insert into public.faqs (id, question, question_hi, answer, answer_hi, category, display_order, created_at, updated_at) values ('6175c26b-3453-4965-8640-74aa8780c7e7', 'Which brands of agricultural machinery do you deal in?', null, 'Shyamali Krishna Automobile is an authorised dealer and distributor for Maschio Gaspardo, Sitara AgroTech, Gobind Alloys (Govind), Agrimax, and Hazarix implements. We also offer harvesting machinery from select established OEMs. Our multi-brand portfolio lets you choose equipment matched to your soil, crop, and tractor rather than being limited to a single make.', null, 'General', 1, '2026-08-11T15:51:34.75285+00:00', '2026-08-11T15:51:34.75285+00:00') on conflict (id) do nothing;
insert into public.faqs (id, question, question_hi, answer, answer_hi, category, display_order, created_at, updated_at) values ('cd5cbc5c-81e6-41c4-b06f-6bcb0e31d188', 'Do you provide after-sales service and spare parts?', null, 'Yes. We provide after-sales service for the machinery we supply, with technicians familiar with the implements. We maintain a stock of genuine spare parts and wear components — blades, tines, bearings, seals, and belts — so that your equipment stays in working order through the season.', null, 'Service', 2, '2026-08-11T15:51:34.75285+00:00', '2026-08-11T15:51:34.75285+00:00') on conflict (id) do nothing;
insert into public.faqs (id, question, question_hi, answer, answer_hi, category, display_order, created_at, updated_at) values ('e0df1a35-5085-4038-91d8-6feea718416b', 'Can you help me choose the right implement for my tractor and crop?', null, 'Yes. We assess your soil type, crop rotation, tractor horsepower, and operating scale, then recommend the most suitable implement from our portfolio. You can request a consultation through the contact form or call us directly.', null, 'General', 3, '2026-08-11T15:51:34.75285+00:00', '2026-08-11T15:51:34.75285+00:00') on conflict (id) do nothing;
insert into public.faqs (id, question, question_hi, answer, answer_hi, category, display_order, created_at, updated_at) values ('7f08cc6f-f58c-4c76-bd31-996741d14611', 'Do you help with finance and EMI for purchasing machinery?', null, 'We assist farmers in accessing financing options for machinery purchases. We help you understand the documentation required and coordinate with financing channels to facilitate tractor-implement loans and EMI arrangements. Contact us for guidance specific to your requirement.', null, 'Finance', 4, '2026-08-11T15:51:34.75285+00:00', '2026-08-11T15:51:34.75285+00:00') on conflict (id) do nothing;
insert into public.faqs (id, question, question_hi, answer, answer_hi, category, display_order, created_at, updated_at) values ('e4ae4caa-7ce6-45b9-bf83-43f01de5d867', 'Do you help with government subsidy schemes for farm machinery?', null, 'Yes. We help farmers understand and apply for applicable government subsidy schemes for agricultural machinery. We provide information on scheme eligibility, documentation, and the application process, and coordinate where required. Subsidy availability depends on the scheme and your eligibility.', null, 'Subsidy', 5, '2026-08-11T15:51:34.75285+00:00', '2026-08-11T15:51:34.75285+00:00') on conflict (id) do nothing;
insert into public.faqs (id, question, question_hi, answer, answer_hi, category, display_order, created_at, updated_at) values ('f530a1ee-efbe-49bd-ab91-75dc12f1d7e0', 'What is your service area?', null, 'We are based in Nawada, Bihar and serve Nawada and adjoining districts. For institutional and bulk enquiries, we can discuss service beyond the immediate region — please contact us with your requirement.', null, 'General', 6, '2026-08-11T15:51:34.75285+00:00', '2026-08-11T15:51:34.75285+00:00') on conflict (id) do nothing;
insert into public.faqs (id, question, question_hi, answer, answer_hi, category, display_order, created_at, updated_at) values ('e8a90e8b-d25c-4fef-99f7-e84c48b7f40e', 'How do I get a demonstration of a machine before purchase?', null, 'You can request a demonstration through the contact form, by calling us, or by using the enquiry option on any product page. We will assess your requirement and arrange a demonstration or field visit where feasible.', null, 'General', 7, '2026-08-11T15:51:34.75285+00:00', '2026-08-11T15:51:34.75285+00:00') on conflict (id) do nothing;
insert into public.faqs (id, question, question_hi, answer, answer_hi, category, display_order, created_at, updated_at) values ('3ffa7e44-449d-42ac-b42c-6225021c9c81', 'What are your operating hours?', null, 'We operate Monday to Saturday, 9:00 AM to 7:00 PM. Sunday visits are available on appointment. You can contact us by phone or WhatsApp during operating hours, or submit an enquiry through the website at any time.', null, 'General', 8, '2026-08-11T15:51:34.75285+00:00', '2026-08-11T15:51:34.75285+00:00') on conflict (id) do nothing;

-- job_categories: skipped (Could not find the table 'public.job_categories' in the sche)

-- job_locations: skipped (Could not find the table 'public.job_locations' in the schem)

-- employment_types: skipped (Could not find the table 'public.employment_types' in the sc)

-- jobs: no rows

-- job_location_map: skipped (Could not find the table 'public.job_location_map' in the sc)

-- job_applications: no rows

-- leads: no rows

-- lead_notes: no rows

commit;
