-- ============================================================================
-- Shyamali Krishna Automobile — COMPLETE database setup
--
-- Run this ONE file in the Supabase SQL Editor. It works in both situations:
--
--   A) A BRAND NEW, EMPTY project  -> creates every table the site needs.
--   B) The EXISTING project        -> creates only what is missing and adds
--                                     the recruitment columns to the tables
--                                     that already exist.
--
-- It is fully idempotent and non-destructive: every statement is
-- "if not exists" or "on conflict do nothing". It never drops a table, never
-- deletes a row, and is safe to run twice.
--
-- AFTER running this on a NEW project, load your content with:
--     supabase/seed/0002_data_export.sql
-- (generated by `npm run export-data` from the old project)
-- ============================================================================

begin;

create extension if not exists pgcrypto;

-- ############################################################################
-- SECTION 1 — Site content
-- ############################################################################

create table if not exists public.site_settings (
  key        text primary key,
  value      text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.categories (
  id                     uuid primary key default gen_random_uuid(),
  name                   text not null,
  name_hi                text,
  slug                   text not null unique,
  description            text,
  description_hi         text,
  short_description      text,
  short_description_hi   text,
  icon                   text,
  image_url              text,
  display_order          integer not null default 0,
  seo_title              text,
  seo_description        text,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now()
);

create table if not exists public.partners (
  id                          uuid primary key default gen_random_uuid(),
  name                        text not null,
  name_hi                     text,
  slug                        text not null unique,
  tagline                     text,
  tagline_hi                  text,
  positioning                 text,
  positioning_hi              text,
  overview                    text,
  overview_hi                 text,
  partnership_context         text,
  partnership_context_hi      text,
  why_partnership_matters     text,
  why_partnership_matters_hi  text,
  origin_country              text,
  logo_url                    text,
  hero_image_url              text,
  seo_title                   text,
  seo_description             text,
  display_order               integer not null default 0,
  created_at                  timestamptz not null default now(),
  updated_at                  timestamptz not null default now()
);

create table if not exists public.products (
  id                 uuid primary key default gen_random_uuid(),
  name               text not null,
  name_hi            text,
  slug               text not null unique,
  category_id        uuid references public.categories (id) on delete set null,
  partner_id         uuid references public.partners (id) on delete set null,
  positioning        text,
  positioning_hi     text,
  overview           text,
  overview_hi        text,
  features           text,
  features_hi        text,
  benefits           text,
  benefits_hi        text,
  applications       text,
  applications_hi    text,
  crops              text,
  soil_conditions    text,
  operator_scale     text,
  tractor_hp         text,
  working_width      text,
  weight             text,
  blade_tine_config  text,
  gearbox_drive      text,
  rpm                text,
  warranty           text,
  financing          text,
  financing_hi       text,
  subsidy            text,
  subsidy_hi         text,
  primary_image_url  text,
  gallery_images     text[],
  seo_title          text,
  seo_description    text,
  is_published       boolean not null default true,
  display_order      integer not null default 0,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

create index if not exists products_category_idx on public.products (category_id);
create index if not exists products_partner_idx  on public.products (partner_id);

create table if not exists public.services (
  id                    uuid primary key default gen_random_uuid(),
  name                  text not null,
  name_hi               text,
  slug                  text not null unique,
  short_description     text,
  short_description_hi  text,
  overview              text,
  overview_hi           text,
  what_we_cover         text,
  what_we_cover_hi      text,
  icon                  text,
  image_url             text,
  seo_title             text,
  seo_description       text,
  display_order         integer not null default 0,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);

-- The live project predates this column; the app's type declares it.
alter table public.services add column if not exists image_url text;

create table if not exists public.resources (
  id               uuid primary key default gen_random_uuid(),
  title            text not null,
  title_hi         text,
  slug             text not null unique,
  type             text not null default 'article',
  excerpt          text,
  excerpt_hi       text,
  content          text,
  content_hi       text,
  seo_title        text,
  seo_description  text,
  is_published     boolean not null default true,
  display_order    integer not null default 0,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

create table if not exists public.faqs (
  id             uuid primary key default gen_random_uuid(),
  question       text not null,
  question_hi    text,
  answer         text not null,
  answer_hi      text,
  category       text,
  display_order  integer not null default 0,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

-- ############################################################################
-- SECTION 2 — Recruitment lookups (managed from the admin portal)
-- ############################################################################

create table if not exists public.job_categories (
  id            uuid primary key default gen_random_uuid(),
  name          text not null,
  name_hi       text,
  slug          text not null,
  description   text,
  active        boolean not null default true,
  display_order integer not null default 0,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
create unique index if not exists job_categories_slug_key on public.job_categories (slug);
create unique index if not exists job_categories_name_key on public.job_categories (lower(name));

create table if not exists public.job_locations (
  id            uuid primary key default gen_random_uuid(),
  name          text not null,
  name_hi       text,
  slug          text not null,
  active        boolean not null default true,
  display_order integer not null default 0,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
create unique index if not exists job_locations_slug_key on public.job_locations (slug);
create unique index if not exists job_locations_name_key on public.job_locations (lower(name));

create table if not exists public.employment_types (
  id            uuid primary key default gen_random_uuid(),
  name          text not null,
  slug          text not null,
  active        boolean not null default true,
  display_order integer not null default 0,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
create unique index if not exists employment_types_slug_key on public.employment_types (slug);
create unique index if not exists employment_types_name_key on public.employment_types (lower(name));

-- ############################################################################
-- SECTION 3 — Jobs
-- ############################################################################

create table if not exists public.jobs (
  id                            uuid primary key default gen_random_uuid(),
  title                         text not null,
  title_hi                      text,
  slug                          text not null,
  department                    text,
  location                      text,
  employment_type               text,
  experience                    text,
  summary                       text,
  summary_hi                    text,
  responsibilities              text,
  responsibilities_hi           text,
  requirements                  text,
  requirements_hi               text,
  preferred_qualifications      text,
  preferred_qualifications_hi   text,
  what_we_offer                 text,
  what_we_offer_hi              text,
  application_deadline          date,
  status                        text not null default 'draft',
  seo_title                     text,
  seo_description               text,
  published_at                  timestamptz,
  created_at                    timestamptz not null default now(),
  updated_at                    timestamptz not null default now()
);

-- Recruitment columns. Separate ALTERs so this file also upgrades an existing
-- `jobs` table that was created before the recruitment system existed.
alter table public.jobs add column if not exists category_id        uuid references public.job_categories (id) on delete set null;
alter table public.jobs add column if not exists vacancies          integer not null default 1;
alter table public.jobs add column if not exists experience_level   text;
alter table public.jobs add column if not exists min_experience     text;
alter table public.jobs add column if not exists max_experience     text;
alter table public.jobs add column if not exists description        text;
alter table public.jobs add column if not exists description_hi     text;
alter table public.jobs add column if not exists skills             text;
alter table public.jobs add column if not exists salary_type        text;
alter table public.jobs add column if not exists salary_min         numeric;
alter table public.jobs add column if not exists salary_max         numeric;
alter table public.jobs add column if not exists salary_period      text;
alter table public.jobs add column if not exists salary_negotiable  boolean not null default false;
alter table public.jobs add column if not exists contact_info       text;
alter table public.jobs add column if not exists additional_notes   text;

create unique index if not exists jobs_slug_key      on public.jobs (slug);
create index        if not exists jobs_category_idx  on public.jobs (category_id);
create index        if not exists jobs_status_idx    on public.jobs (status);

-- Older rows used 'archived'; the portal speaks draft/published/closed.
update public.jobs set status = 'closed' where status = 'archived';

create table if not exists public.job_location_map (
  job_id      uuid not null references public.jobs (id) on delete cascade,
  location_id uuid not null references public.job_locations (id) on delete cascade,
  primary key (job_id, location_id)
);
create index if not exists job_location_map_location_idx on public.job_location_map (location_id);

-- ############################################################################
-- SECTION 4 — Applications
-- ############################################################################

create table if not exists public.job_applications (
  id                     uuid primary key default gen_random_uuid(),
  job_id                 uuid references public.jobs (id) on delete set null,
  job_slug               text,
  full_name              text not null,
  email                  text not null,
  phone                  text not null,
  current_location       text,
  highest_qualification  text,
  years_of_experience    text,
  resume_url             text,
  resume_filename        text,
  cover_letter           text,
  linkedin_url           text,
  portfolio_url          text,
  status                 text not null default 'new',
  internal_notes         text,
  is_general             boolean not null default false,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now()
);

-- Snapshot + notification tracking. Snapshots freeze what the applicant
-- actually applied to, so the record still reads correctly after the job is
-- renamed, recategorised or deleted.
alter table public.job_applications add column if not exists job_title_snapshot           text;
alter table public.job_applications add column if not exists category_snapshot            text;
alter table public.job_applications add column if not exists preferred_location           text;
alter table public.job_applications add column if not exists address                      text;
alter table public.job_applications add column if not exists notification_status          text not null default 'pending';
alter table public.job_applications add column if not exists notification_attempts        integer not null default 0;
alter table public.job_applications add column if not exists notification_last_attempt_at timestamptz;
alter table public.job_applications add column if not exists notification_error           text;

create index if not exists job_applications_job_idx     on public.job_applications (job_id);
create index if not exists job_applications_created_idx on public.job_applications (created_at desc);
create index if not exists job_applications_status_idx  on public.job_applications (status);
create index if not exists job_applications_dupe_idx    on public.job_applications (lower(email), job_id, created_at desc);

-- ############################################################################
-- SECTION 5 — Leads / CRM
-- ############################################################################

create table if not exists public.leads (
  id                       uuid primary key default gen_random_uuid(),
  lead_type                text not null default 'contact',
  name                     text not null,
  phone                    text not null,
  whatsapp                 text,
  email                    text,
  district_village         text,
  enquiry_type             text,
  message                  text,
  product_id               uuid references public.products (id) on delete set null,
  product_name             text,
  partner_name             text,
  category_name            text,
  tractor_hp               text,
  service_type             text,
  preferred_callback_time  text,
  source_page              text not null default '',
  language                 text not null default 'en',
  status                   text not null default 'new',
  priority                 text not null default 'medium',
  assigned_to              text,
  is_archived              boolean not null default false,
  created_at               timestamptz not null default now(),
  updated_at               timestamptz not null default now()
);
create index if not exists leads_created_idx on public.leads (created_at desc);
create index if not exists leads_status_idx  on public.leads (status);

create table if not exists public.lead_notes (
  id         uuid primary key default gen_random_uuid(),
  lead_id    uuid not null references public.leads (id) on delete cascade,
  note       text not null,
  author     text,
  created_at timestamptz not null default now()
);
create index if not exists lead_notes_lead_idx on public.lead_notes (lead_id);

-- ############################################################################
-- SECTION 6 — Admin
-- ############################################################################

create table if not exists public.admin_sessions (
  id         uuid primary key default gen_random_uuid(),
  token      text not null unique,
  expires_at timestamptz not null,
  ip_address text,
  user_agent text,
  created_at timestamptz not null default now()
);
create index if not exists admin_sessions_expiry_idx on public.admin_sessions (expires_at);

create table if not exists public.admin_activity (
  id          uuid primary key default gen_random_uuid(),
  action      text not null,
  entity_type text,
  entity_id   text,
  description text,
  created_at  timestamptz not null default now()
);
-- Backs the login / application rate limiters.
create index if not exists admin_activity_rate_idx on public.admin_activity (action, entity_type, created_at desc);

-- Single row. Empty until the first login, which hashes ADMIN_PASSWORD into it
-- with scrypt; from then on the env var is ignored. Only a hash is ever stored.
create table if not exists public.admin_credentials (
  id                   smallint primary key default 1 check (id = 1),
  password_hash        text not null,
  must_change_password boolean not null default false,
  password_changed_at  timestamptz not null default now(),
  last_login_at        timestamptz,
  updated_at           timestamptz not null default now()
);

create table if not exists public.admin_password_resets (
  id         uuid primary key default gen_random_uuid(),
  token_hash text not null,
  expires_at timestamptz not null,
  used_at    timestamptz,
  ip_address text,
  created_at timestamptz not null default now()
);
create unique index if not exists admin_password_resets_token_key  on public.admin_password_resets (token_hash);
create index        if not exists admin_password_resets_expiry_idx on public.admin_password_resets (expires_at);

-- ############################################################################
-- SECTION 7 — Row Level Security
--
-- The browser holds only the anon key. It may READ published content, and it
-- may INSERT a lead (that is what the contact forms do) — nothing else. Every
-- admin write goes through the server with the service-role key, which
-- bypasses RLS entirely.
-- ############################################################################

alter table public.site_settings         enable row level security;
alter table public.categories            enable row level security;
alter table public.partners              enable row level security;
alter table public.products              enable row level security;
alter table public.services              enable row level security;
alter table public.resources             enable row level security;
alter table public.faqs                  enable row level security;
alter table public.job_categories        enable row level security;
alter table public.job_locations         enable row level security;
alter table public.employment_types      enable row level security;
alter table public.jobs                  enable row level security;
alter table public.job_location_map      enable row level security;
alter table public.job_applications      enable row level security;
alter table public.leads                 enable row level security;
alter table public.lead_notes            enable row level security;
alter table public.admin_sessions        enable row level security;
alter table public.admin_activity        enable row level security;
alter table public.admin_credentials     enable row level security;
alter table public.admin_password_resets enable row level security;

-- Public read -----------------------------------------------------------------
drop policy if exists "public read site_settings"    on public.site_settings;
drop policy if exists "public read categories"       on public.categories;
drop policy if exists "public read partners"         on public.partners;
drop policy if exists "public read products"         on public.products;
drop policy if exists "public read services"         on public.services;
drop policy if exists "public read resources"        on public.resources;
drop policy if exists "public read faqs"             on public.faqs;
drop policy if exists "public read job_categories"   on public.job_categories;
drop policy if exists "public read job_locations"    on public.job_locations;
drop policy if exists "public read employment_types" on public.employment_types;
drop policy if exists "public read jobs"             on public.jobs;
drop policy if exists "public read job_location_map" on public.job_location_map;

create policy "public read site_settings"    on public.site_settings    for select to anon, authenticated using (true);
create policy "public read categories"       on public.categories       for select to anon, authenticated using (true);
create policy "public read partners"         on public.partners         for select to anon, authenticated using (true);
create policy "public read products"         on public.products         for select to anon, authenticated using (is_published);
create policy "public read services"         on public.services         for select to anon, authenticated using (true);
create policy "public read resources"        on public.resources        for select to anon, authenticated using (is_published);
create policy "public read faqs"             on public.faqs             for select to anon, authenticated using (true);
create policy "public read job_categories"   on public.job_categories   for select to anon, authenticated using (active);
create policy "public read job_locations"    on public.job_locations    for select to anon, authenticated using (active);
create policy "public read employment_types" on public.employment_types for select to anon, authenticated using (active);
create policy "public read job_location_map" on public.job_location_map for select to anon, authenticated using (true);

-- Published and closed jobs are public; a DRAFT never is. A closed vacancy has
-- to stay readable so its old URL can say "no longer accepting applications"
-- instead of 404-ing on someone who followed a link.
create policy "public read jobs" on public.jobs
  for select to anon, authenticated
  using (status in ('published', 'closed'));

-- Public insert ---------------------------------------------------------------
-- The callback / enquiry / service forms write here with the anon key. INSERT
-- only: a visitor must never be able to read anyone else's enquiry back out.
drop policy if exists "public insert leads" on public.leads;
create policy "public insert leads" on public.leads for insert to anon, authenticated with check (true);

-- No policies at all for: job_applications, lead_notes, admin_sessions,
-- admin_activity, admin_credentials, admin_password_resets.
-- RLS on + no policy = the anon key sees and writes nothing. Applications are
-- written by POST /api/careers/apply, which verifies the job server-side first.
revoke all on public.job_applications from anon;

-- ############################################################################
-- SECTION 8 — Private storage bucket for CVs
-- ############################################################################

insert into storage.buckets (id, name, public)
values ('applications', 'applications', false)
on conflict (id) do update set public = false;

-- No anon policies: uploads and downloads both go through the server, which
-- mints a 5-minute signed URL for an authenticated admin.

-- ############################################################################
-- SECTION 9 — Seed data
-- ############################################################################

-- Job categories, derived from what this business actually does.
insert into public.job_categories (name, name_hi, slug, description, display_order) values
  ('Sales',                'बिक्री',                  'sales',                'Counter and field sales of tractors and farm implements.',     1),
  ('Field Operations',     'फील्ड संचालन',            'field-operations',     'On-farm demonstrations, delivery, and machine commissioning.', 2),
  ('Service & Technical',  'सेवा एवं तकनीकी',         'service-technical',    'After-sales service, repair, and technician roles.',           3),
  ('Spare Parts & Stores', 'स्पेयर पार्ट्स एवं स्टोर', 'spare-parts-stores',   'Parts counter, inventory, and warehouse handling.',            4),
  ('Administration',       'प्रशासन',                 'administration',       'Office administration, records, and documentation.',           5),
  ('Computer / IT',        'कंप्यूटर / आईटी',          'computer-it',          'Data entry, billing software, and computer operations.',       6),
  ('Accounts & Finance',   'लेखा एवं वित्त',          'accounts-finance',     'Billing, accounts, EMI and subsidy paperwork.',                7),
  ('Management',           'प्रबंधन',                 'management',           'Branch, territory, and team leadership roles.',                8)
on conflict (slug) do nothing;

-- The six salesman territories. The admin can add more at any time.
insert into public.job_locations (name, slug, display_order) values
  ('Kashichak',  'kashichak',  1),
  ('Pakribarma', 'pakribarma', 2),
  ('Nawada',     'nawada',     3),
  ('Meskaur',    'meskaur',    4),
  ('Roh',        'roh',        5),
  ('Kawakol',    'kawakol',    6)
on conflict (slug) do nothing;

insert into public.employment_types (name, slug, display_order) values
  ('Full Time',  'full-time',  1),
  ('Part Time',  'part-time',  2),
  ('Contract',   'contract',   3),
  ('Internship', 'internship', 4),
  ('Temporary',  'temporary',  5),
  ('Other',      'other',      6)
on conflict (slug) do nothing;

-- The three initial vacancies. Only the supplied facts are set — salary,
-- qualifications, experience and responsibilities are left for the admin.
insert into public.jobs (title, slug, category_id, department, vacancies, employment_type, status, published_at)
select 'Computer Operator', 'computer-operator', c.id, c.name, 3, 'Full Time', 'published', now()
from public.job_categories c where c.slug = 'computer-it'
on conflict (slug) do nothing;

insert into public.jobs (title, slug, category_id, department, vacancies, employment_type, status, published_at)
select 'Salesman', 'salesman', c.id, c.name, 6, 'Full Time', 'published', now()
from public.job_categories c where c.slug = 'sales'
on conflict (slug) do nothing;

insert into public.jobs (title, slug, category_id, department, vacancies, employment_type, status, published_at)
select 'Sales Manager', 'sales-manager', c.id, c.name, 2, 'Full Time', 'published', now()
from public.job_categories c where c.slug = 'management'
on conflict (slug) do nothing;

-- Salesman is open in all six territories.
insert into public.job_location_map (job_id, location_id)
select j.id, l.id from public.jobs j cross join public.job_locations l
where j.slug = 'salesman'
  and l.slug in ('kashichak', 'pakribarma', 'nawada', 'meskaur', 'roh', 'kawakol')
on conflict do nothing;

-- The other two are head-office roles in Nawada.
insert into public.job_location_map (job_id, location_id)
select j.id, l.id from public.jobs j cross join public.job_locations l
where j.slug in ('computer-operator', 'sales-manager') and l.slug = 'nawada'
on conflict do nothing;

-- Refresh the denormalised location snapshot.
update public.jobs j
set location = sub.names
from (
  select m.job_id, string_agg(l.name, ', ' order by l.display_order) as names
  from public.job_location_map m
  join public.job_locations l on l.id = m.location_id
  group by m.job_id
) sub
where sub.job_id = j.id;

-- Careers email addresses. Falls back to the general business email if one is
-- already on file, so nothing has to be retyped.
insert into public.site_settings (key, value)
select 'careers_email',
       coalesce((select value from public.site_settings where key = 'email'), 'info@shyamalikrishna.com')
on conflict (key) do nothing;

insert into public.site_settings (key, value)
values ('careers_recovery_email', 'info@shyamalikrishna.com')
on conflict (key) do nothing;

commit;

-- ============================================================================
-- Verify
-- ============================================================================
--   select table_name from information_schema.tables
--    where table_schema = 'public' order by table_name;
--
--   select title, slug, vacancies, status, location from public.jobs;
--   select name, slug, active from public.job_locations order by display_order;
